language: java

branches:
  only:
    - WLANAudit3

before_install:
  - sudo apt-get install libc6-dev-i386
  - sudo apt-get install lib32ncurses5-dev
  - sudo apt-get install libx11-dev
  - sudo apt-get install g++-multilib
  - sudo apt-get install lib32z1-dev
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz
  - tar -zxf android-sdk_r21-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter tools,platform-tools,android-8,android-16,addon-google_apis-google-16,extra-android-support,extra-google-admob_ads_sdk,extra-google-analytics_sdk,extra-google-gcm,extra-google-play_apk_expansion,extra-google-play_billing,extra-google-play_licensing --no-ui --force --no-https -a

script: ant build-debug
